swagger: '2.0'
info:
  description: This is the API document for the COP 4331 Contacts app
  version: 1.0.0
  title: Contacts app
  # Nicholas Borzilleri(enter contact info)
  # Daniel Gomez (enter contact info)
  # Dylan Money (enter contact info)
  contact:
    email: ni792013@ucf.edu
    
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /Login.php:
    post:
      tags:
      - Users
      summary: Logs into the contacts app
      operationId: doLogin
      description: Logs in to colors app
      
      consumes:
      - application/json
      produces:
      - in: body
        name: loginItem
        description: Login
        schema:
          $ref: '#/definitions/Login
          
      responses:
        200:
          description: OK
        404:
          description: URL Not Found
        
  /AddContact.php:
    post:
      tags:
      - Contacts
      summary: Adds a contact
      operationId: addContact
      description: Adds a contact to the contact app
    database
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: contactItem
        description: Contact
        schema:
          $ref: '#/definitions/Contact'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found
  /SearchContacts.aspx:
    post:
      tags:
      - Search
      summary: Searches contact list
      operationId: searchContact
      description: Searches contact from the contacts database
      consumes:
      - application/json
      produces:
      - application/json
      paremeters:
      - in: body
        name: searchItem
        description: Contact Search
        schema:
          $ref: '#/definitions/Search'
      responses:
        200:
          description: OK
        404:
          description: URL Not Found
          
  
 Login:
  type: object
  required:
  - login
  - password
  properties:
    login:
      type: string
      example: "fred"
    password:
      type: string
      
      example: "secret"
  Contact: #I can add more properties idk if I need the email or phone number for the contacts
    type: object
    required:
    - userId
    - contact
    - phoneNumber
    properties:
      userId:
        type: integer
        example: 1
      contact:
        type: string
        example: "John"
      phoneNumber:
        type: string
        example: "516-778-9904"
  Search:
    type: object
    required:
    - userId
    - search
    properties:
      userId:
        type: integer
        example: 1
      search:
        type: string
        example: "mar"
        
host: contacts.com
basePath: /LAMPAPI
schemes:
- http