swagger: '2.0'
info:
  description: This is the API document for the COP 4331 Contacts app
  version: 1.0.0
  title: Contacts app
  # Nicholas Borzilleri(enter contact info)
  # Daniel Gomez (enter contact info)
  # Dylan Money (enter contact info)
  contact:
    email: ni792013@ucf.edu
    
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

host: 137.184.185.65 #change to whatever out url/domain name is
basePath: /LAMPAPI
schemes:
- http
consumes:
  - application/json
produces:
  - application/json


paths:
  /Login.php:
    post:
      tags:
      - Users
      summary: Logs in and returns user info
      operationId: doLogin
      description: Expects plain password; backend hashes with MD5 to compare 
      parameters:
      - in: body
        name: loginItem
        required: true
        description: Login
        schema:
          $ref: '#/definitions/Login'
          
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/LoginResponse'
        400:
          description: Missing login or password
          schema:
            $ref: '#/definitions/Error'
        401:
          description: Invalid credentials
          schema: 
            $ref: '#/definitions/Error'
        404:
          description: URL Not Found
        500:
          description: Server/DB error
          schema:
            $ref: '#/definitions/Error'
        
  /AddContact.php:
    post:
      tags:
      - Contacts
      summary: Adds a contact
      operationId: addContact
      description: Adds a contact to the contact app database
      parameters:
      - in: body
        name: contactItem
        required: true
        description: Contact
        schema:
          $ref: '#/definitions/ContactAddRequest'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/UserCreatedResponse'
        400:
          description: Validation error (missing fields)
          schema:
           $ref: '#/definitions/Error'
        404:
          description: URL Not Found
        409:
          description: Username already exists
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server/DB error
          schema:
            $ref: '#/definitions/Error'
  /SearchContacts.php:
    post:
      tags:
      - Search
      summary: Searches contact list
      operationId: searchContact
      description: Searches contact from the contacts database
      parameters:
      - in: body
        name: searchItem
        required: true
        description: Contact Search
        schema:
          $ref: '#/definitions/Search'
      responses:
        200:
          description: Resluts (possibly empty)
          schema:
            $ref: '#/definitions/SearchResponse'
        400:
          description: Validation error (missing userId)
          schema:
            $ref: '#/definitions/Error'
        404:
          description: URL Not Found
        500:
          description: Server/DB error
          schema:
            $ref: '#/definitions/Error'
  /CreateUsers.php:
    post:
      tags:
      - Create
      summary: Creates a user
      operationId: createUser
      description: Creates a user to login with
      parameters:
      - in: body
        name: createItem
        description: Create User
        required: true
        schema:
          $ref: '#/definitions/Create'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/UserCreatedResponse'
        400:
          description: Validation error (missing fields)
          schema:
            $ref: '#/definitions/Error'
        404:
          description: URL Not Found
        409:
          description: Username already exists
          schema:
            $ref: '#/definitions/Error'
        500:
          description: Server/DB error
          schema:
            $ref: '#/definitions/Error'
          
definitions:
  Error:
    type: object
    required:
    - error
    properties:
      error:
        type: string
        example: "Invalid credentials"
  Login:
    type: object
    required:
    - login
    - password
    properties:
      login:
        type: string
        example: "fred"
      password:
        type: string
        example: "secret"
  LoginResponse:
    type: object
    required:
    - id
    - firstName
    - lastName
    - error
    properties:
      id:
        type: integer
        example: 12
      firstName:
        type: string
        example: "John"
      lastName:
        type: string
        example: 'Snow'
      error:
        type: string
        example: ""
  Search:
    type: object
    required:
    - userId
    - search
    properties:
      userId:
        type: integer
        example: 1
      search:
        type: string
        example: "mar"
  Create:
    type: object
    required:
    - login
    - password
    - firstname
    - lastname
    properties:
      login:
        type: string
        example: "carl0672"
      password:
        type: string
        example: "secret1212"
      firstname:
        type: string
        example: "santos"
      lastname:
        type: string
        example: "smith"
  UserCreatedResponse:
    type: object
    required:
    - id
    - firstName
    - lastName
    - error
    properties:
      id:
        type: integer
        example: 12
      firstName:
        type: string
        example: "John"
      lastName:
        type: string
        example: "Snow"
      error:
        type: string
        example: ""
  ContactAddRequest:
    type: object
    required:
    - userId
    - contact
    properties:
      userId:
        type: integer
        example: 12
      contact:
        type: string
        example: "Maria Rodriguez"
  ContactAddResponse:
    type: object
    required:
    - id
    - userId
    - name
    - error
    properties:
      id:
        type: integer
        example: 101
      userId:
        type: integer
        example: 12
      name:
        type: string
        example: "John Snow"
      error:
        type: string
        example: ""
  SearchResponse:
    type: object
    required:
    - results
    - error
    properties:
      results:
        type: array
        items:
          type: string
        example: ["John Snow", "Mark Hamil"]
      error:
        type: string
        example: ""
